# Generated by Django 4.2.7 on 2023-11-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="army_source_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
