# Generated by Django 4.2.7 on 2023-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="rounds",
            field=models.IntegerField(default=5),
        ),
    ]
