# Generated by Django 4.2.7 on 2023-11-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_pairing"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairing",
            name="event",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="data.event"
            ),
            preserve_default=False,
        ),
    ]
