# Generated by Django 4.2.7 on 2023-11-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_pairing_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairing",
            name="source_id",
            field=models.CharField(default={}, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pairing",
            name="source_json",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
