# Generated by Django 4.2.7 on 2023-11-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0008_alter_pairing_player1_alter_pairing_player2"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="army_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
