# Generated by Django 4.2.7 on 2023-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0010_alter_list_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="player_created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="list",
            name="player_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
