# Generated by Django 4.2.7 on 2023-11-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0011_alter_list_player_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pairing",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pairings",
                to="data.event",
            ),
        ),
    ]
