# Generated by Django 4.2.7 on 2023-11-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0012_alter_pairing_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="faction",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="faction_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="ghb",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="ghb_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="subfaction",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="subfaction_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
