# Generated by Django 4.2.7 on 2023-11-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0015_remove_list_ghb_remove_list_ghb_id_event_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="season",
            field=models.IntegerField(null=True),
        ),
    ]
