# Generated by Django 4.2.7 on 2023-11-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0016_alter_event_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="rounds",
            field=models.IntegerField(default=5, null=True),
        ),
    ]
