# Generated by Django 4.2.7 on 2023-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0017_alter_event_rounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairing",
            name="gpt_parse_error",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pairing",
            name="gpt_parsed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pairing",
            name="regexp_parsed",
            field=models.BooleanField(default=False),
        ),
    ]
