# Generated by Django 4.2.7 on 2023-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0020_alter_list_faction_alter_list_grand_strategy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="game_type",
            field=models.IntegerField(
                choices=[(0, "Age of Sigmar"), (1, "Warhammer 40k")],
                default=0,
                null=True,
            ),
        ),
    ]
