# Generated by Django 4.2.7 on 2023-12-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0021_event_game_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="source_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="list",
            name="source_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pairing",
            name="source_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="participant",
            name="army_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="army_source_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="source_id",
            field=models.CharField(max_length=255),
        ),
    ]
