# Generated by Django 4.2.9 on 2024-02-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_event_name_alter_event_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='faction',
            field=models.CharField(choices=[('Stormcast Eternals', 'Stormcast Eternals'), ('Daughters of Khaine', 'Daughters of Khaine'), ('Fyreslayers', 'Fyreslayers'), ('Idoneth Deepkin', 'Idoneth Deepkin'), ('Kharadron Overlords', 'Kharadron Overlords'), ('Lumineth Realm-lords', 'Lumineth Realm-lords'), ('Sylvaneth', 'Sylvaneth'), ('Seraphon', 'Seraphon'), ('Cities of Sigmar', 'Cities of Sigmar'), ('Slaves to Darkness', 'Slaves to Darkness'), ('Blades of Khorne', 'Blades of Khorne'), ('Disciples of Tzeentch', 'Disciples of Tzeentch'), ('Hedonites of Slaanesh', 'Hedonites of Slaanesh'), ('Maggotkin of Nurgle', 'Maggotkin of Nurgle'), ('Skaven', 'Skaven'), ('Beasts of Chaos', 'Beasts of Chaos'), ('Legion of Azgorh', 'Legion of Azgorh'), ('Flesh-eater Courts', 'Flesh-eater Courts'), ('Nighthaunt', 'Nighthaunt'), ('Ossiarch Bonereapers', 'Ossiarch Bonereapers'), ('Soulblight Gravelords', 'Soulblight Gravelords'), ('Orruk Warclans', 'Orruk Warclans'), ('Gloomspite Gitz', 'Gloomspite Gitz'), ('Sons of Behemat', 'Sons of Behemat'), ('Ogor Mawtribes', 'Ogor Mawtribes'), ('Legion of the First Prince', 'Legion of the First Prince')], max_length=255, null=True),
        ),
    ]
