# Generated by Django 4.2.9 on 2024-02-07 22:54


from django.db import migrations

from data.models import SNL


def update_name_for_existing_events(apps, schema_editor):
    Event = apps.get_model("data", "Event")
    for event in Event.objects.filter(source=SNL).filter(name=""):
        event.name = event.source_json["name"]
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_list_faction'),
    ]

    operations = [
        migrations.RunPython(update_name_for_existing_events),
    ]
