# Generated by Django 4.2.16 on 2024-10-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_list_drops_list_manifestation_lore_list_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairing',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='player1_list',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='player1_result',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='player1_score',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='player2_list',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='player2_result',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='player2_score',
        ),
        migrations.AddField(
            model_name='pairing',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pairing',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='data.participant'),
        ),
        migrations.AddField(
            model_name='pairing',
            name='loser_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_list', to='data.list'),
        ),
        migrations.AddField(
            model_name='pairing',
            name='loser_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pairing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='data.participant'),
        ),
        migrations.AddField(
            model_name='pairing',
            name='winner_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_list', to='data.list'),
        ),
        migrations.AddField(
            model_name='pairing',
            name='winner_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['event', 'round'], name='data_pairin_event_i_358af7_idx'),
        ),
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['winner'], name='data_pairin_winner__b159d7_idx'),
        ),
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['loser'], name='data_pairin_loser_i_9a5f06_idx'),
        ),
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['is_draw'], name='data_pairin_is_draw_ff3186_idx'),
        ),
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['scenario'], name='data_pairin_scenari_de9a96_idx'),
        ),
    ]
