# Generated by Django 4.2.18 on 2025-02-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_alter_list_subfaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='faction',
            field=models.CharField(blank=True, choices=[('Beasts of Chaos', 'Beasts of Chaos'), ('Blades of Khorne', 'Blades of Khorne'), ('Bonesplitterz', 'Bonesplitterz'), ('Cities of Sigmar', 'Cities of Sigmar'), ('Daughters of Khaine', 'Daughters of Khaine'), ('Disciples of Tzeentch', 'Disciples of Tzeentch'), ('Flesh-Eater Courts', 'Flesh-Eater Courts'), ('Fyreslayers', 'Fyreslayers'), ('Gloomspite Gitz', 'Gloomspite Gitz'), ('Hedonites of Slaanesh', 'Hedonites of Slaanesh'), ('Idoneth Deepkin', 'Idoneth Deepkin'), ('Ironjawz', 'Ironjawz'), ('Kharadron Overlords', 'Kharadron Overlords'), ('Kruleboyz', 'Kruleboyz'), ('Lumineth Realm-lords', 'Lumineth Realm-lords'), ('Maggotkin of Nurgle', 'Maggotkin of Nurgle'), ('Nighthaunt', 'Nighthaunt'), ('Ogor Mawtribes', 'Ogor Mawtribes'), ('Ossiarch Bonereapers', 'Ossiarch Bonereapers'), ('Seraphon', 'Seraphon'), ('Skaven', 'Skaven'), ('Slaves to Darkness', 'Slaves to Darkness'), ('Sons of Behemat', 'Sons of Behemat'), ('Soulblight Gravelords', 'Soulblight Gravelords'), ('Stormcast Eternals', 'Stormcast Eternals'), ('Sylvaneth', 'Sylvaneth')], db_index=True, max_length=255, null=True, verbose_name='Faction'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='loser_score',
            field=models.IntegerField(blank=True, help_text='Score of the loser.', null=True, verbose_name='Loser Score'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='winner_score',
            field=models.IntegerField(blank=True, help_text='Score of the winner.', null=True, verbose_name='Winner Score'),
        ),
    ]
