# Generated by Django 4.2.7 on 2023-11-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Even",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("source", models.IntegerField(choices=[(0, "BCP"), (1, "TSN")])),
                ("source_id", models.CharField(max_length=100)),
                ("source_json", models.JSONField()),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("photo_url", models.URLField(null=True)),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lists.location",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["name", "start_date"], name="lists_even_name_cfea4b_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="lists_even_start_d_ae902f_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="lists_even_end_dat_2fdf15_idx"
                    ),
                    models.Index(
                        fields=["source", "source_id"],
                        name="lists_even_source_d3afe8_idx",
                    ),
                ],
            },
        ),
    ]
