# Generated by Django 4.2.7 on 2023-11-17 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0002_even_created_at_even_updated_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Even",
            new_name="Event",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="lists_event_name_4ef749_idx",
            old_name="lists_even_name_cfea4b_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="lists_event_start_d_ef097f_idx",
            old_name="lists_even_start_d_ae902f_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="lists_event_end_dat_8ce8a0_idx",
            old_name="lists_even_end_dat_2fdf15_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="lists_event_source_2ed155_idx",
            old_name="lists_even_source_d3afe8_idx",
        ),
    ]
