# Generated by Django 4.2.7 on 2023-11-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0003_rename_even_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="players_count",
            field=models.IntegerField(null=True),
        ),
    ]
